apiVersion: v1
kind: Service
metadata:
  labels:
    app: streamer
  name: streamer
spec:
  ports:
  - port: 9000
  selector:
    app: streamer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: streamer
  name: streamer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: streamer
    spec:
      containers:
      - name: streamer
        image: arkocal/oisp-streamer
        ports:
        - containerPort: 9000
        env:
        - name: OISP_KAFKA_CONFIG
          valueFrom:
            configMapKeyRef:
              name: oisp-config
              key: kafka
        - name: OISP_KEYCLOAK_CONFIG
          valueFrom:
            configMapKeyRef:
              name: oisp-config
              key: keycloak
        - name: OISP_STREAMER_CONFIG
          valueFrom:
            configMapKeyRef:
              name: streamer-config
              key: streamer
#        - name: KAFKA_URI
#          value: "oisp-kafka-headless:9092"
#        - name: WSS_PORT
#          value: "9000"
