apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: beamservices.oisp.org
spec:
  scope: Namespaced
  group: oisp.org
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: BeamService
    plural: beamservices
    singular: beamservice
    shortNames:
      - bs
    # Again, included from tutorial:
    # https://medium.com/swlh/building-a-kubernetes-operator-in-python-with-zalandos-kopf-37c311d8edff
    # not used yet
    # additionalPrinterColumns:
    #   name: Type
    #   type: string
