apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: beamservices.oisp.org
spec:
  scope: Namespaced
  group: oisp.org
  versions:
    - name: v1
      served: true
      storage: true
#      schema:
#        openAPIV3Schema:
#          type: object
#          properties:
#            spec:
#              type: object
#              properties:
#                entryClass:
#                  type: string
#                args:
#                  type: object
#                url:
#                  type: string
#                jarId:
#                  type: string
#                jobId:
#                  type: string
#          required: ["spec.entryClass", "spec.args", "spec.url"]
  names:
    kind: BeamService
    plural: beamservices
    singular: beamservice
    shortNames:
      - bs
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: beamsqlstatementsets.oisp.org
spec:
  scope: Namespaced
  group: oisp.org
  versions:
    - name: v1alpha1
      served: true
      storage: true
  names:
    kind: BeamSqlStatementSet
    plural: beamsqlstatementsets
    singular: beamsqlstatementset
    shortNames:
      - bsqls
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: beamsqltables.oisp.org
spec:
  scope: Namespaced
  group: oisp.org
  versions:
    - name: v1alpha1
      served: true
      storage: true
  names:
    kind: BeamSqlTable
    plural: beamsqltables
    singular: beamsqltable
    shortNames:
      - bsqlt