apiVersion: apps/v1
kind: Deployment
metadata:
  name: op
spec:
  selector:
    matchLabels:
      app: op
  template:
    metadata:
      labels:
        app: op
    spec:
      serviceAccountName: beamservices-operator
      containers:
      - image: arkocal/oisp_services_operator:latest
        name: op
